// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk8gF_PXI29XmeTe1Woifq9W_fx2MnE2U',
    appId: '1:1058632461872:android:73ec8f40b03eba8be347f5',
    messagingSenderId: '1058632461872',
    projectId: 'chatbox-2926c',
    databaseURL: 'https://chatbox-2926c-default-rtdb.firebaseio.com',
    storageBucket: 'chatbox-2926c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfs1e2gRRptNywu41fn-gDiO8rwI6bSaU',
    appId: '1:1058632461872:ios:d064dbcf1d631f15e347f5',
    messagingSenderId: '1058632461872',
    projectId: 'chatbox-2926c',
    databaseURL: 'https://chatbox-2926c-default-rtdb.firebaseio.com',
    storageBucket: 'chatbox-2926c.appspot.com',
    androidClientId: '1058632461872-ccf12aisgsg3kk900b7t4cn17abmppij.apps.googleusercontent.com',
    iosClientId: '1058632461872-njaqm8fdmpttmn44vo7dp45ldk5am2o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitenotes',
  );
}
